"""Автогенерированные метки настроек OrcaSlicer.

Не редактировать вручную. Пересобрать:
    python3 tools/gen_setting_labels.py --source <PrintConfig.cpp> \
        --i18n "<OrcaSlicer>/resources/i18n" --version <версия>

Версия OrcaSlicer: 2.5.0-dev
Дата генерации: 2026-09-19
"""

# pylint: disable=too-many-lines,line-too-long

# LABELS[язык][id настройки] = метка в интерфейсе OrcaSlicer.
LABELS: dict[str, dict[str, str]] = {
    "en": {
        'accel_to_decel_enable': 'Enable accel_to_decel',
        'accel_to_decel_factor': 'accel_to_decel',
        'activate_air_filtration': 'Activate air filtration',
        'activate_chamber_temp_control': 'Activate temperature control',
        'adaptive_bed_mesh_margin': 'Mesh margin',
        'adaptive_layer_height': 'Adaptive layer height',
        'adaptive_pressure_advance': 'Enable adaptive pressure advance (beta)',
        'adaptive_pressure_advance_bridges': 'Static pressure advance for bridges',
        'adaptive_pressure_advance_model': 'Adaptive pressure advance measurements (beta)',
        'adaptive_pressure_advance_overhangs': 'Enable adaptive pressure advance within features (beta)',
        'additional_cooling_fan_speed': 'Fan speed',
        'additional_fan_full_speed_layer': 'Full fan speed at layer',
        'align_infill_direction_to_model': 'Align directions to model',
        'align_xy': 'Align XY',
        'allow_mix_temp': 'Allow filaments with high/low temperature to be printed together',
        'allow_multicolor_oneplate': 'Allow multiple colors on one plate',
        'allow_newer_file': 'Allow 3MF with newer version to be sliced',
        'allow_rotations': 'Allow rotation when arranging',
        'alternate_extra_wall': 'Alternate extra wall',
        'arrange': 'Arrange Options',
        'assemble': 'Assemble',
        'autosave': 'Autosave',
        'auxiliary_fan': 'Auxiliary part cooling fan',
        'avoid_extrusion_cali_region': 'Avoid extrusion calibrate region when arranging',
        'bbl_calib_mark_logo': 'Show auto-calibration marks',
        'bbl_use_printhost': 'Use 3rd-party print host',
        'bed_custom_model': 'Bed custom model',
        'bed_custom_texture': 'Bed custom texture',
        'bed_exclude_area': 'Excluded bed area',
        'bed_mesh_max': 'Bed mesh max',
        'bed_mesh_min': 'Bed mesh min',
        'bed_mesh_probe_distance': 'Probe point distance',
        'bed_temperature_formula': 'Bed temperature type',
        'before_layer_change_gcode': 'Before layer change G-code',
        'best_object_pos': 'Best object position',
        'bottom_layer_direction': 'Bottom layer direction',
        'bottom_shell_layers': 'Bottom shell layers',
        'bottom_shell_thickness': 'Bottom shell thickness',
        'bottom_solid_infill_flow_ratio': 'Bottom surface flow ratio',
        'bottom_surface_density': 'Bottom surface density',
        'bottom_surface_filament_id': 'Bottom surface',
        'bottom_surface_fill_order': 'Bottom surface fill order',
        'bottom_surface_pattern': 'Bottom surface pattern',
        'bridge_acceleration': 'Bridge',
        'bridge_angle': 'External bridge infill direction',
        'bridge_density': 'External bridge density',
        'bridge_flow': 'Bridge flow ratio',
        'bridge_line_width': 'Bridge',
        'bridge_no_support': "Don't support bridges",
        'bridge_speed': 'External',
        'brim_ears': 'Brim ears',
        'brim_ears_detection_length': 'Brim ear detection radius',
        'brim_ears_max_angle': 'Brim ear max angle',
        'brim_ears_outer_only': 'Brim ears outer only',
        'brim_flow_ratio': 'Brim flow ratio',
        'brim_object_gap': 'Brim-object gap',
        'brim_type': 'Brim type',
        'brim_use_efc_outline': 'Brim follows compensated outline',
        'brim_width': 'Brim width',
        'center': 'Center',
        'center_of_surface_pattern': 'Center surface pattern on',
        'chamber_minimal_temperature': 'Minimal',
        'chamber_temperature': 'Chamber temperature',
        'change_extrusion_role_gcode': 'Change extrusion role G-code',
        'change_filament_gcode': 'Change filament G-code',
        'clone_objects': 'Clone Objects',
        'close_additional_fan_first_x_layers': 'For the first',
        'close_fan_the_first_x_layers': 'No cooling for the first',
        'combine_brims': 'Combine brims',
        'compatible_printers': 'Select printers',
        'compatible_printers_condition': 'Condition',
        'compatible_prints': 'Select profiles',
        'compatible_prints_condition': 'Condition',
        'complete_print_exhaust_fan_speed': 'Fan speed',
        'config_compatibility': 'Forward-compatibility rule when loading configurations from config files and project files (3MF, AMF).',
        'convert_unit': 'Convert Unit',
        'cool_plate_temp': 'Other layers',
        'cool_plate_temp_initial_layer': 'First layer',
        'cooling_filter_enabled': 'Use cooling filter',
        'cooling_tube_length': 'Cooling tube length',
        'cooling_tube_retraction': 'Cooling tube position',
        'copy': 'Copy',
        'counterbore_hole_bridging': 'Bridge counterbore holes',
        'curr_bed_type': 'Bed type',
        'current_extruder': 'Current extruder',
        'current_object_idx': 'Current object index',
        'cut': 'Cut',
        'cut_grid': 'Cut',
        'cut_x': 'Cut',
        'cut_y': 'Cut',
        'datadir': 'Data directory',
        'day': 'Day',
        'debug': 'Debug level',
        'default_acceleration': 'Normal printing',
        'default_bed_type': 'Default bed type',
        'default_filament_colour': 'Default color',
        'default_filament_profile': 'Default filament profile',
        'default_jerk': 'Default',
        'default_junction_deviation': 'Junction Deviation',
        'default_nozzle_volume_type': 'Default Nozzle Volume Type.',
        'default_print_profile': 'Default process profile',
        'deretract_speed_extruder_change': 'Deretraction speed (extruder change)',
        'deretraction_speed': 'Deretraction speed',
        'detect_narrow_internal_solid_infill': 'Detect narrow internal solid infills',
        'detect_overhang_wall': 'Detect overhang walls',
        'detect_thin_wall': 'Detect thin walls',
        'disable_m73': 'Disable set remaining print time',
        'dont_filter_internal_bridges': 'Filter out small internal bridges',
        'dont_slow_down_outer_wall': "Don't slow down outer walls",
        'downward_check': 'Downward machines check',
        'downward_settings': 'Downward machines settings',
        'draft_shield': 'Draft shield',
        'duplicate_grid': 'Duplicate by grid',
        'during_print_exhaust_fan_speed': 'Fan speed',
        'e_position': 'Absolute E position',
        'e_restart_extra': 'Extra de-retraction',
        'e_retracted': 'Retraction',
        'elefant_foot_compensation': 'Elephant foot compensation',
        'elefant_foot_compensation_layers': 'Elephant foot compensation layers',
        'elefant_foot_layers_density': 'Elephant foot layers density',
        'emit_machine_limits_to_gcode': 'Emit limits to G-code',
        'enable_arc_fitting': 'Arc fitting',
        'enable_extra_bridge_layer': 'Extra bridge layers (beta)',
        'enable_filament_dynamic_map': 'Enable filament dynamic map',
        'enable_filament_ramming': 'Enable filament ramming',
        'enable_mixed_color_sublayer': 'Mixed color sublayer',
        'enable_overhang_bridge_fan': 'Force cooling for overhangs and bridges',
        'enable_overhang_speed': 'Slow down for overhangs',
        'enable_power_loss_recovery': 'Power Loss Recovery',
        'enable_pressure_advance': 'Enable pressure advance',
        'enable_prime_tower': 'Enable',
        'enable_support': 'Enable support',
        'enable_timelapse': 'Enable timelapse for print',
        'enable_tower_interface_cooldown_during_tower': 'Cool down from interface boost during prime tower',
        'enable_tower_interface_features': 'Enable tower interface features',
        'enable_wrapping_detection': 'Enable clumping detection',
        'enforce_support_layers': 'Enforce support for the first',
        'eng_plate_temp': 'Other layers',
        'eng_plate_temp_initial_layer': 'First layer',
        'ensure_on_bed': 'Ensure on bed',
        'ensure_vertical_shell_thickness': 'Ensure vertical shell thickness',
        'exclude_object': 'Exclude objects',
        'export_3mf': 'Export 3MF',
        'export_amf': 'Export AMF',
        'export_gcode': 'Export G-code',
        'export_obj': 'Export OBJ',
        'export_settings': 'Export Settings',
        'export_sla': 'Export SLA',
        'export_slicedata': 'Export slicing data',
        'export_stl': 'Export STL',
        'export_stls': 'Export multiple STLs',
        'export_svg': 'Export SVG',
        'extra_loading_move': 'Extra loading distance',
        'extra_perimeters_on_overhangs': 'Extra perimeters on overhangs',
        'extra_solid_infills': 'Insert solid layers',
        'extruded_volume': 'Volume per extruder',
        'extruded_volume_total': 'Total volume',
        'extruded_weight': 'Weight per extruder',
        'extruded_weight_total': 'Total weight',
        'extruder': 'Extruder',
        'extruder_ams_count': 'Extruder AMS count',
        'extruder_clearance_dist_to_rod': 'Distance to rod',
        'extruder_clearance_height_to_lid': 'Height to lid',
        'extruder_clearance_height_to_rod': 'Height to rod',
        'extruder_clearance_radius': 'Radius',
        'extruder_colour': 'Extruder Color',
        'extruder_nozzle_count': 'extruder nozzle count',
        'extruder_nozzle_stats': 'Extruder nozzle stats',
        'extruder_nozzle_volume_type': 'Extruder nozzle volume type',
        'extruder_offset': 'Extruder offset',
        'extruder_printable_area': 'Extruder printable area',
        'extruder_printable_height': 'Extruder printable height',
        'extruder_type': 'Type',
        'extruder_variant_list': 'Extruder variant list',
        'extrusion_rate_smoothing_external_perimeter_only': 'Apply only on external features',
        'fan_cooling_layer_time': 'Layer time',
        'fan_direction': 'Fan direction',
        'fan_kickstart': 'Fan kick-start time',
        'fan_max_speed': 'Fan speed',
        'fan_min_speed': 'Fan speed',
        'fan_speedup_overhangs': 'Only overhangs',
        'fan_speedup_time': 'Fan speed-up time',
        'farthest_point_timelapse': 'Farthest point timelapse',
        'filament_adaptive_volumetric_speed': 'Adaptive volumetric speed',
        'filament_adhesiveness_category': 'Adhesiveness Category',
        'filament_change_extrusion_role_gcode': 'Change extrusion role G-code (filament)',
        'filament_change_length': 'Filament ramming length',
        'filament_change_length_nc': 'Hotend change',
        'filament_colour': 'Color',
        'filament_cooling_before_tower': 'Wipe tower cooling',
        'filament_cooling_final_speed': 'Speed of the last cooling move',
        'filament_cooling_initial_speed': 'Speed of the first cooling move',
        'filament_cooling_moves': 'Number of cooling moves',
        'filament_cost': 'Price',
        'filament_density': 'Density',
        'filament_diameter': 'Diameter',
        'filament_end_gcode': 'End G-code',
        'filament_extruder_compatibility': 'Filament-extruder compatibility',
        'filament_extruder_id': 'Filament extruder ID',
        'filament_extruder_variant': "Filament's extruder variant",
        'filament_flow_ratio': 'Flow ratio',
        'filament_flush_temp': 'Flush temperature',
        'filament_flush_temp_fast': 'Flush temperature',
        'filament_flush_volumetric_speed': 'Flush volumetric speed',
        'filament_ironing_flow': 'Ironing flow',
        'filament_ironing_inset': 'Ironing inset',
        'filament_ironing_spacing': 'Ironing line spacing',
        'filament_ironing_speed': 'Ironing speed',
        'filament_is_mixed': 'Is mixed filament',
        'filament_is_support': 'Support material',
        'filament_loading_speed': 'Loading speed',
        'filament_loading_speed_start': 'Loading speed at the start',
        'filament_map': 'Filament map to extruder',
        'filament_map_2': 'Filament map plus for multi nozzle',
        'filament_map_mode': 'filament mapping mode',
        'filament_max_volumetric_speed': 'Max volumetric speed',
        'filament_minimal_purge_on_wipe_tower': 'Minimal purge on wipe tower',
        'filament_mixed_components': 'Mixed filament components',
        'filament_mixed_gradient': 'Mixed filament gradient',
        'filament_mixed_gradient_curve': 'Mixed filament gradient curve',
        'filament_mixed_gradient_per_part': 'Mixed filament per-part gradient',
        'filament_mixed_gradient_range': 'Mixed filament gradient range',
        'filament_mixed_sublayer_ratios': 'Mixed filament sublayer ratios',
        'filament_multitool_ramming': 'Enable ramming for multi-tool setups',
        'filament_multitool_ramming_flow': 'Multi-tool ramming flow',
        'filament_multitool_ramming_volume': 'Multi-tool ramming volume',
        'filament_notes': 'Filament notes',
        'filament_pre_cooling_temperature': 'Extruder change',
        'filament_pre_cooling_temperature_nc': 'Hotend change',
        'filament_preheat_temperature_delta': 'Preheat temperature delta',
        'filament_preset': 'Filament preset name',
        'filament_prime_volume': 'Filament change',
        'filament_prime_volume_nc': 'Hotend change',
        'filament_printable': 'Filament printable',
        'filament_ramming_parameters': 'Ramming parameters',
        'filament_ramming_travel_time': 'Extruder change',
        'filament_ramming_travel_time_nc': 'Hotend change',
        'filament_ramming_volumetric_speed': 'Extruder change',
        'filament_ramming_volumetric_speed_nc': 'Hotend change',
        'filament_retract_length_nc': 'length when change hotend',
        'filament_self_index': 'Filament self index',
        'filament_shrink': 'Shrinkage (XY)',
        'filament_shrinkage_compensation_z': 'Shrinkage (Z)',
        'filament_soluble': 'Soluble material',
        'filament_stamping_distance': 'Stamping distance measured from the center of the cooling tube',
        'filament_stamping_loading_speed': 'Stamping loading speed',
        'filament_start_gcode': 'Start G-code',
        'filament_toolchange_delay': 'Delay after unloading',
        'filament_tower_interface_pre_extrusion_dist': 'Interface layer pre-extrusion distance',
        'filament_tower_interface_pre_extrusion_length': 'Interface layer pre-extrusion length',
        'filament_tower_interface_print_temp': 'Interface layer print temperature',
        'filament_tower_interface_purge_volume': 'Interface layer purge length',
        'filament_tower_ironing_area': 'Tower ironing area',
        'filament_type': 'Type',
        'filament_unloading_speed': 'Unloading speed',
        'filament_unloading_speed_start': 'Unloading speed at the start',
        'filament_vendor': 'Vendor',
        'file_start_gcode': 'File header G-code',
        'filename_format': 'Filename format',
        'fill_multiline': 'Fill Multiline',
        'filter_out_gap_fill': 'Filter out tiny gaps',
        'first_layer_flow_ratio': 'First layer flow ratio',
        'first_layer_print_convex_hull': 'First layer convex hull',
        'first_layer_print_max': 'Top-right corner of the first layer bounding box',
        'first_layer_print_min': 'Bottom-left corner of the first layer bounding box',
        'first_layer_print_sequence': 'First layer print sequence',
        'first_layer_print_size': 'Size of the first layer bounding box',
        'first_layer_sequence_choice': 'First layer filament sequence',
        'first_x_layer_fan_speed': 'Fan speed',
        'flashforge_serial_number': 'Serial Number',
        'flush_into_infill': "Flush into objects' infill",
        'flush_into_objects': 'Flush into this object',
        'flush_into_support': "Flush into objects' support",
        'flush_multiplier': 'Flush multiplier',
        'flush_multiplier_fast': 'Flush multiplier (Fast mode)',
        'flush_volumes_matrix': 'Purging volumes',
        'full_fan_speed_layer': 'Full fan speed at layer',
        'fuzzy_skin': 'Fuzzy skin',
        'fuzzy_skin_first_layer': 'Apply fuzzy skin to first layer',
        'fuzzy_skin_layers_between_ripple_offset': 'Layers between ripple offset',
        'fuzzy_skin_mode': 'Fuzzy skin generator mode',
        'fuzzy_skin_noise_type': 'Fuzzy skin noise type',
        'fuzzy_skin_octaves': 'Fuzzy Skin Noise Octaves',
        'fuzzy_skin_persistence': 'Fuzzy skin noise persistence',
        'fuzzy_skin_point_distance': 'Fuzzy skin point distance',
        'fuzzy_skin_ripple_offset': 'Ripple offset',
        'fuzzy_skin_ripples_per_layer': 'Number of ripples per layer',
        'fuzzy_skin_scale': 'Fuzzy skin feature size',
        'fuzzy_skin_thickness': 'Fuzzy skin thickness',
        'gap_fill_flow_ratio': 'Gap fill flow ratio',
        'gap_fill_target': 'Apply gap fill',
        'gap_infill_speed': 'Gap infill',
        'gcode_add_line_number': 'Add line number',
        'gcode_comments': 'Verbose G-code',
        'gcode_flavor': 'G-code flavor',
        'gcode_label_objects': 'Label objects',
        'gcode_skip_config_block': 'Skip G-code config block',
        'gcodeviewer': 'G-code viewer',
        'grab_length': 'Grab length',
        'ground_face_normal': 'Ground face by normal',
        'ground_face_point': 'Ground face at point',
        'ground_largest_face': 'Ground largest face',
        'gyroid_optimized': 'Z-buckling bias optimization (experimental)',
        'has_filament_switcher': 'Has filament switcher',
        'has_single_extruder_multi_material_priming': 'Has single extruder MM priming',
        'has_wipe_tower': 'Has wipe tower',
        'head_wrap_detect_zone': 'Head wrap detect zone',
        'help': 'Help',
        'help_fff': 'Help (FFF options)',
        'help_sla': 'Help (SLA options)',
        'high_current_on_filament_swap': 'High extruder current on filament swap',
        'hole_to_polyhole': 'Convert holes to polyholes',
        'hole_to_polyhole_max_edges': 'Maximum Polyhole edge count',
        'hole_to_polyhole_threshold': 'Polyhole detection margin',
        'hole_to_polyhole_twisted': 'Polyhole twist',
        'host_type': 'Host Type',
        'hot_plate_temp': 'Other layers',
        'hot_plate_temp_initial_layer': 'First layer',
        'hour': 'Hour',
        'idle_temperature': 'Idle temperature',
        'ignore_nonexistent_config': 'Ignore non-existent config files',
        'independent_support_layer_height': 'Independent support layer height',
        'infill_anchor': 'Sparse infill anchor length',
        'infill_anchor_max': 'Maximum length of the infill anchor',
        'infill_combination': 'Infill combination',
        'infill_combination_max_layer_height': 'Infill combination - Max layer height',
        'infill_direction': 'Sparse infill direction',
        'infill_jerk': 'Infill',
        'infill_lock_depth': 'Infill lock depth',
        'infill_overhang_angle': 'Infill overhang angle',
        'infill_shift_step': 'Infill shift step',
        'infill_wall_overlap': 'Infill/wall overlap',
        'info': 'Output Model Info',
        'inherits': 'Inherits profile',
        'initial_extruder': 'Initial extruder',
        'initial_filament_type': 'Initial filament type',
        'initial_layer_acceleration': 'First layer',
        'initial_layer_fan_speed': 'First layer fan speed',
        'initial_layer_infill_speed': 'First layer infill',
        'initial_layer_jerk': 'First layer',
        'initial_layer_line_width': 'First layer',
        'initial_layer_min_bead_width': 'First layer minimum wall width',
        'initial_layer_print_height': 'First layer height',
        'initial_layer_speed': 'First layer',
        'initial_layer_travel_acceleration': 'First layer travel',
        'initial_layer_travel_jerk': 'First layer travel',
        'initial_layer_travel_speed': 'First layer travel speed',
        'initial_tool': 'Initial tool',
        'inner_wall_acceleration': 'Inner wall',
        'inner_wall_filament_id': 'Inner walls',
        'inner_wall_flow_ratio': 'Inner wall flow ratio',
        'inner_wall_jerk': 'Inner wall',
        'inner_wall_line_width': 'Inner wall',
        'inner_wall_speed': 'Inner wall',
        'input_filename_base': 'Input filename without extension',
        'input_shaping_damp_x': 'X',
        'input_shaping_damp_y': 'Y',
        'input_shaping_emit': 'Emit input shaping',
        'input_shaping_freq_x': 'X',
        'input_shaping_freq_y': 'Y',
        'input_shaping_type': 'Input shaper type',
        'inspect_mesh': 'Inspect mesh (JSON to stdout)',
        'inspect_paint': 'Inspect paint (JSON to stdout)',
        'interface_shells': 'Interface shells',
        'interlocking_beam': 'Use beam interlocking',
        'interlocking_beam_layer_count': 'Interlocking beam layers',
        'interlocking_beam_width': 'Interlocking beam width',
        'interlocking_boundary_avoidance': 'Interlocking boundary avoidance',
        'interlocking_depth': 'Interlocking depth',
        'interlocking_orientation': 'Interlocking direction',
        'internal_bridge_angle': 'Internal bridge infill direction',
        'internal_bridge_density': 'Internal bridge density',
        'internal_bridge_fan_speed': 'Internal bridges fan speed',
        'internal_bridge_flow': 'Internal bridge flow ratio',
        'internal_bridge_speed': 'Internal',
        'internal_solid_filament_id': 'Internal solid infill',
        'internal_solid_infill_acceleration': 'Internal solid infill',
        'internal_solid_infill_flow_ratio': 'Internal solid infill flow ratio',
        'internal_solid_infill_line_width': 'Internal solid infill',
        'internal_solid_infill_pattern': 'Internal solid infill pattern',
        'internal_solid_infill_speed': 'Internal solid infill',
        'ironing_angle': 'Ironing angle offset',
        'ironing_angle_fixed': 'Fixed ironing angle',
        'ironing_expansion': 'Ironing expansion',
        'ironing_fan_speed': 'Ironing fan speed',
        'ironing_flow': 'Ironing flow',
        'ironing_inset': 'Ironing inset',
        'ironing_pattern': 'Ironing Pattern',
        'ironing_spacing': 'Ironing line spacing',
        'ironing_speed': 'Ironing speed',
        'ironing_type': 'Ironing type',
        'is_extruder_used': 'Is extruder used?',
        'is_infill_first': 'Print infill first',
        'lateral_lattice_angle_1': 'Lateral lattice angle 1',
        'lateral_lattice_angle_2': 'Lateral lattice angle 2',
        'layer_change_gcode': 'Layer change G-code',
        'layer_height': 'Layer height',
        'layer_num': 'Layer number',
        'layer_z': 'Layer Z',
        'lightning_overhang_angle': 'Lightning overhang angle',
        'lightning_prune_angle': 'Prune angle',
        'lightning_straightening_angle': 'Straightening angle',
        'line_width': 'Default',
        'load': 'Load config file',
        'load_assemble_list': 'Load assemble list',
        'load_custom_gcodes': 'Load custom G-code',
        'load_defaultfila': 'Load default filaments',
        'load_filament_ids': 'Load filament IDs',
        'load_filaments': 'Load Filament Settings',
        'load_settings': 'Load General Settings',
        'load_slicedata': 'Load slicing data',
        'logfile': 'Log file',
        'long_retractions_when_cut': 'Long retraction when cut (beta)',
        'long_retractions_when_ec': 'Long retraction when extruder change',
        'machine_end_gcode': 'End G-code',
        'machine_hotend_change_time': 'Hotend change time',
        'machine_load_filament_time': 'Filament load time',
        'machine_pause_gcode': 'Pause G-code',
        'machine_start_gcode': 'Start G-code',
        'machine_tool_change_time': 'Tool change time',
        'machine_unload_filament_time': 'Filament unload time',
        'make_overhang_printable': 'Make overhangs printable',
        'make_overhang_printable_angle': 'Make overhangs printable - Maximum angle',
        'make_overhang_printable_hole_size': 'Make overhangs printable - Hole area',
        'makerlab_name': 'MakerLab name',
        'makerlab_version': 'MakerLab version',
        'manual_filament_change': 'Manual Filament Change',
        'master_extruder_id': 'Master extruder id',
        'max_bridge_length': 'Max bridge length',
        'max_layer_height': 'Max',
        'max_layer_z': 'Maximal layer Z',
        'max_resonance_avoidance_speed': 'Max',
        'max_travel_detour_distance': 'Avoid crossing walls - Max detour length',
        'max_volumetric_extrusion_rate_slope': 'Extrusion rate smoothing',
        'max_volumetric_extrusion_rate_slope_segment_length': 'Smoothing segment length',
        'metadata_name': 'Metadata name list',
        'metadata_value': 'Metadata value list',
        'min_bead_width': 'Minimum wall width',
        'min_feature_size': 'Minimum feature size',
        'min_layer_height': 'Min',
        'min_length_factor': 'Minimum wall length',
        'min_resonance_avoidance_speed': 'Min',
        'min_save': 'Minimum save',
        'min_skirt_length': 'Skirt minimum extrusion length',
        'min_width_top_surface': 'One wall threshold',
        'minimum_sparse_infill_area': 'Minimum sparse infill threshold',
        'minute': 'Minute',
        'mmu_segmented_region_interlocking_depth': 'Interlocking depth of a segmented region',
        'mmu_segmented_region_max_width': 'Maximum width of a segmented region',
        'month': 'Month',
        'mstpp': 'mstpp',
        'mtcpp': 'mtcpp',
        'no_check': 'No check',
        'normal_print_time': 'Print time (normal mode)',
        'normative_check': 'Normative check',
        'notes': 'Configuration notes',
        'nozzle_diameter': 'Nozzle diameter',
        'nozzle_height': 'Nozzle height',
        'nozzle_hrc': 'Nozzle HRC',
        'nozzle_temperature': 'Other layers',
        'nozzle_temperature_initial_layer': 'First layer',
        'nozzle_temperature_range_high': 'Max',
        'nozzle_temperature_range_low': 'Min',
        'nozzle_type': 'Nozzle type',
        'nozzle_volume': 'Nozzle volume',
        'nozzle_volume_type': 'Nozzle Volume Type',
        'num_extruders': 'Number of extruders',
        'num_instances': 'Number of instances',
        'num_objects': 'Number of objects',
        'num_printing_extruders': 'Number of printing extruders',
        'only_one_wall_first_layer': 'Only one wall on first layer',
        'only_one_wall_top': 'Only one wall on top surfaces',
        'ooze_prevention': 'Enable',
        'orient': 'Orient Options',
        'other_layers_print_sequence': 'Other layers print sequence',
        'other_layers_print_sequence_nums': 'The number of other layers print sequence',
        'other_layers_sequence_choice': 'Other layers filament sequence',
        'outer_wall_acceleration': 'Outer wall',
        'outer_wall_filament_id': 'Outer walls',
        'outer_wall_flow_ratio': 'Outer wall flow ratio',
        'outer_wall_jerk': 'Outer wall',
        'outer_wall_line_width': 'Outer wall',
        'outer_wall_speed': 'Outer wall',
        'output': 'Output File',
        'outputdir': 'Output directory',
        'overhang_1_4_speed': '10%',
        'overhang_2_4_speed': '25%',
        'overhang_3_4_speed': '50%',
        'overhang_4_4_speed': '75%',
        'overhang_fan_speed': 'Overhangs and external bridges fan speed',
        'overhang_fan_threshold': 'Overhang cooling activation threshold',
        'overhang_flow_ratio': 'Overhang flow ratio',
        'overhang_reverse': 'Reverse on even',
        'overhang_reverse_internal_only': 'Reverse only internal perimeters',
        'overhang_reverse_threshold': 'Reverse threshold',
        'parallel_printheads_bed_exclude_areas': 'Parallel printheads bed exclude areas',
        'parallel_printheads_count': 'Parallel printheads count',
        'parking_pos_retraction': 'Filament parking position',
        'part_cooling_fan_min_pwm': 'Minimum non-zero part cooling fan speed',
        'pellet_flow_coefficient': 'Pellet flow coefficient',
        'pellet_modded_printer': 'Pellet Modded Printer',
        'physical_extruder_map': 'Map the logical extruder to physical extruder',
        'physical_printer_preset': 'Physical printer name',
        'pipe': 'Send progress to pipe',
        'plugins': 'Plugins Used',
        'position': 'Position',
        'post_process': 'Post-processing Scripts',
        'precise_outer_wall': 'Precise wall',
        'precise_z_height': 'Precise Z height',
        'preferred_orientation': 'Preferred orientation',
        'preheat_steps': 'Preheat steps',
        'preheat_time': 'Preheat time',
        'preset_names': 'Printer preset names',
        'pressure_advance': 'Pressure advance',
        'prime_tower_brim_width': 'Brim width',
        'prime_tower_enable_framework': 'Internal ribs',
        'prime_tower_infill_gap': 'Infill gap',
        'prime_tower_skip_points': 'Skip points',
        'prime_tower_width': 'Width',
        'prime_volume': 'Prime volume',
        'prime_volume_mode': 'Prime volume mode',
        'print_bed_max': 'Top-right corner of print bed bounding box',
        'print_bed_min': 'Bottom-left corner of print bed bounding box',
        'print_bed_size': 'Size of the print bed bounding box',
        'print_extruder_id': 'Print extruder id',
        'print_extruder_variant': "Print's extruder variant",
        'print_flow_ratio': 'Flow ratio',
        'print_host': 'Hostname, IP or URL',
        'print_host_webui': 'Device UI',
        'print_order': 'Intra-layer order',
        'print_preset': 'Print preset name',
        'print_sequence': 'Print sequence',
        'print_time': 'Print time (normal mode)',
        'print_time_sec': 'Print time (seconds)',
        'printable_area': 'Printable area',
        'printable_height': 'Printable height',
        'printer_agent': 'Printer Agent',
        'printer_extruder_id': 'Printer extruder id',
        'printer_extruder_variant': "Printer's extruder variant",
        'printer_model': 'Printer type',
        'printer_notes': 'Printer notes',
        'printer_preset': 'Printer preset name',
        'printer_structure': 'Printer structure',
        'printer_technology': 'Printer technology',
        'printer_variant': 'Printer variant',
        'printhost_apikey': 'API Key / Password',
        'printhost_authorization_type': 'Authorization Type',
        'printhost_cafile': 'HTTPS CA File',
        'printhost_password': 'Password',
        'printhost_port': 'Printer',
        'printhost_ssl_ignore_revoke': 'Ignore HTTPS certificate revocation checks',
        'printhost_user': 'User',
        'printing_by_object_gcode': 'Between Object G-code',
        'printing_filament_types': 'Used filament types',
        'process_change_extrusion_role_gcode': 'Change extrusion role G-code (process)',
        'purge_in_prime_tower': 'Purge in prime tower',
        'raft_contact_distance': 'Raft contact Z distance',
        'raft_expansion': 'Raft expansion',
        'raft_first_layer_density': 'First layer density',
        'raft_first_layer_expansion': 'First layer expansion',
        'raft_layers': 'Raft layers',
        'reduce_crossing_wall': 'Avoid crossing walls',
        'reduce_fan_stop_start_freq': 'Keep fan always on',
        'reduce_infill_retraction': 'Reduce infill retraction',
        'relative_bridge_angle': 'Relative bridge angle',
        'repair': 'Repair',
        'repetitions': 'Repetition count',
        'resolution': 'Resolution',
        'resonance_avoidance': 'Resonance avoidance',
        'retract_after_wipe': 'Retract amount after wipe',
        'retract_before_wipe': 'Retract amount before wipe',
        'retract_length_toolchange': 'Retraction Length (Toolchange)',
        'retract_lift_above': 'Only lift Z above',
        'retract_lift_below': 'Only lift Z below',
        'retract_lift_enforce': 'On surfaces',
        'retract_restart_extra': 'Extra length on restart',
        'retract_restart_extra_toolchange': 'Extra length on restart (Toolchange)',
        'retract_when_changing_layer': 'Retract on layer change',
        'retraction_distances_when_cut': 'Retraction distance when cut',
        'retraction_distances_when_ec': 'Retraction distance when extruder change',
        'retraction_length': 'Length',
        'retraction_minimum_travel': 'Travel distance threshold',
        'retraction_speed': 'Retraction speed',
        'role_based_wipe_speed': 'Role base wipe speed',
        'rotate': 'Rotate',
        'rotate_x': 'Rotate around X',
        'rotate_y': 'Rotate around Y',
        'scale': 'Scale per object',
        'scale_to_fit': 'Scale to Fit',
        'scan_first_layer': 'Scan first layer',
        'scarf_angle_threshold': 'Conditional angle threshold',
        'scarf_joint_flow_ratio': 'Scarf joint flow ratio',
        'scarf_joint_speed': 'Scarf joint speed',
        'scarf_overhang_threshold': 'Conditional overhang threshold',
        'seam_gap': 'Seam gap',
        'seam_position': 'Seam position',
        'seam_slope_conditional': 'Conditional scarf joint',
        'seam_slope_entire_loop': 'Scarf around entire wall',
        'seam_slope_inner_walls': 'Scarf joint for inner walls',
        'seam_slope_min_length': 'Scarf length',
        'seam_slope_start_height': 'Scarf start height',
        'seam_slope_steps': 'Scarf steps',
        'seam_slope_type': 'Scarf joint seam (beta)',
        'second': 'Second',
        'separated_infills': 'Separated infills',
        'set_other_flow_ratios': 'Set other flow ratios',
        'silent_mode': 'Silent Mode',
        'silent_print_time': 'Print time (silent mode)',
        'single_extruder_multi_material': 'Single Extruder Multi Material',
        'single_extruder_multi_material_priming': 'Prime all printing extruders',
        'single_instance': 'Single instance mode',
        'single_loop_draft_shield': 'Single loop after first layer',
        'skeleton_infill_density': 'Skeleton infill density',
        'skeleton_infill_line_width': 'Skeleton line width',
        'skin_infill_density': 'Skin infill density',
        'skin_infill_depth': 'Skin infill depth',
        'skin_infill_line_width': 'Skin line width',
        'skip_modified_gcodes': 'Skip modified G-code in 3MF',
        'skip_objects': 'Skip Objects',
        'skirt_distance': 'Skirt distance',
        'skirt_height': 'Skirt height',
        'skirt_loops': 'Skirt loops',
        'skirt_speed': 'Skirt speed',
        'skirt_start_angle': 'Skirt start point',
        'skirt_type': 'Skirt type',
        'slice': 'Slice',
        'slice_closing_radius': 'Slice gap closing radius',
        'slicing_mode': 'Slicing Mode',
        'slicing_pipeline_plugin': 'Slicing Pipeline Plugin',
        'slow_down_for_layer_cooling': 'Slow printing down for better layer cooling',
        'slow_down_layer_time': 'Layer time',
        'slow_down_layers': 'Number of slow layers',
        'slow_down_min_speed': 'Min print speed',
        'slowdown_for_curled_perimeters': 'Slow down for curled perimeters',
        'small_area_infill_flow_compensation': 'Small area flow compensation (beta)',
        'small_area_infill_flow_compensation_model': 'Flow Compensation Model',
        'small_perimeter_speed': 'Small perimeters',
        'small_perimeter_threshold': 'Small perimeters threshold',
        'small_support_perimeter_speed': 'Small support perimeters',
        'small_support_perimeter_threshold': 'Small support perimeters threshold',
        'solid_infill_direction': 'Solid infill direction',
        'solid_infill_rotate_template': 'Solid infill rotation template',
        'spaghetti_detector': 'Enable spaghetti detector',
        'sparse_infill_acceleration': 'Sparse infill',
        'sparse_infill_density': 'Sparse infill density',
        'sparse_infill_filament_id': 'Infill',
        'sparse_infill_flow_ratio': 'Sparse infill flow ratio',
        'sparse_infill_line_width': 'Sparse infill',
        'sparse_infill_pattern': 'Sparse infill pattern',
        'sparse_infill_rotate_template': 'Sparse infill rotation template',
        'sparse_infill_smooth_factor': 'Sparse infill smooth factor',
        'sparse_infill_speed': 'Sparse infill',
        'spiral_finishing_flow_ratio': 'Spiral finishing flow ratio',
        'spiral_mode': 'Spiral vase',
        'spiral_mode_max_xy_smoothing': 'Max XY Smoothing',
        'spiral_mode_smooth': 'Smooth Spiral',
        'spiral_starting_flow_ratio': 'Spiral starting flow ratio',
        'split': 'Split',
        'staggered_inner_seams': 'Staggered inner seams',
        'standby_temperature_delta': 'Temperature variation',
        'start_end_points': 'Start end points',
        'strict': 'Strict mode',
        'supertack_plate_temp': 'Other layers',
        'supertack_plate_temp_initial_layer': 'First layer',
        'support_air_filtration': 'Support air filtration',
        'support_angle': 'Pattern angle',
        'support_base_pattern': 'Base pattern',
        'support_base_pattern_spacing': 'Base pattern spacing',
        'support_bottom_interface_spacing': 'Bottom interface spacing',
        'support_bottom_z_distance': 'Bottom Z distance',
        'support_chamber_temp_control': 'Support controlling chamber temperature',
        'support_critical_regions_only': 'Support critical regions only',
        'support_expansion': 'Normal support expansion',
        'support_fast_purge_mode': 'Support fast purge mode',
        'support_filament': 'Support/raft base',
        'support_flow_ratio': 'Support flow ratio',
        'support_interface_bottom_layers': 'Bottom interface layers',
        'support_interface_filament': 'Support/raft interface',
        'support_interface_flow_ratio': 'Support interface flow ratio',
        'support_interface_loop_pattern': 'Loop pattern interface',
        'support_interface_not_for_body': 'Avoid interface filament for base',
        'support_interface_pattern': 'Interface pattern',
        'support_interface_spacing': 'Top interface spacing',
        'support_interface_speed': 'Support interface',
        'support_interface_top_layers': 'Top interface layers',
        'support_ironing': 'Ironing Support Interface',
        'support_ironing_flow': 'Support Ironing flow',
        'support_ironing_pattern': 'Support Ironing Pattern',
        'support_ironing_spacing': 'Support Ironing line spacing',
        'support_line_width': 'Support',
        'support_material_interface_fan_speed': 'Support interface fan speed',
        'support_multi_bed_types': 'Support multi bed types',
        'support_object_first_layer_gap': 'Support/object first layer gap',
        'support_object_xy_distance': 'Support/object XY distance',
        'support_on_build_plate_only': 'On build plate only',
        'support_parallel_printheads': 'Support parallel printheads',
        'support_remove_small_overhang': 'Ignore small overhangs',
        'support_speed': 'Support',
        'support_style': 'Style',
        'support_threshold_angle': 'Threshold angle',
        'support_threshold_overlap': 'Threshold overlap',
        'support_top_z_distance': 'Top Z distance',
        'support_type': 'Type',
        'sw_renderer': 'Render with a software renderer',
        'symmetric_infill_y_axis': 'Symmetric infill Y axis',
        'temperature_vitrification': 'Softening temperature',
        'template_custom_gcode': 'Custom G-code',
        'textured_cool_plate_temp': 'Other layers',
        'textured_cool_plate_temp_initial_layer': 'First layer',
        'textured_plate_temp': 'Other layers',
        'textured_plate_temp_initial_layer': 'First layer',
        'thick_bridges': 'Thick external bridges',
        'thick_internal_bridges': 'Thick internal bridges',
        'thumbnails': 'G-code thumbnails',
        'thumbnails_format': 'Format of G-code thumbnails',
        'time_cost': 'Time cost',
        'time_lapse_gcode': 'Timelapse G-code',
        'timelapse_type': 'Timelapse',
        'timestamp': 'Timestamp',
        'tool_change_on_wipe_tower': 'Tool change on wipe tower',
        'toolchange_cyclic_first_layer': 'Apply cyclic order to first layer',
        'toolchange_cyclic_order': 'Cyclic order',
        'toolchange_ordering': 'Toolchange ordering',
        'top_bottom_infill_wall_overlap': 'Top/Bottom solid infill/wall overlap',
        'top_layer_direction': 'Top layer direction',
        'top_shell_layers': 'Top shell layers',
        'top_shell_thickness': 'Top shell thickness',
        'top_solid_infill_flow_ratio': 'Top surface flow ratio',
        'top_surface_acceleration': 'Top surface',
        'top_surface_density': 'Top surface density',
        'top_surface_expansion': 'Top surface expansion',
        'top_surface_expansion_direction': 'Top expansion direction',
        'top_surface_expansion_margin': 'Top expansion wall margin',
        'top_surface_filament_id': 'Top surface',
        'top_surface_fill_order': 'Top surface fill order',
        'top_surface_jerk': 'Top surface',
        'top_surface_line_width': 'Top surface',
        'top_surface_pattern': 'Top surface pattern',
        'top_surface_speed': 'Top surface',
        'total_cost': 'Total cost',
        'total_layer_count': 'Total layer count',
        'total_toolchanges': 'Total tool changes',
        'total_weight': 'Total weight',
        'total_wipe_tower_cost': 'Total wipe tower cost',
        'total_wipe_tower_filament': 'Wipe tower volume',
        'travel_acceleration': 'Travel',
        'travel_jerk': 'Travel',
        'travel_slope': 'Traveling angle',
        'travel_speed': 'Travel',
        'travel_speed_z': 'Z travel',
        'tree_support_angle_slow': 'Preferred Branch Angle',
        'tree_support_auto_brim': 'Auto brim width',
        'tree_support_branch_angle': 'Tree support branch angle',
        'tree_support_branch_angle_organic': 'Tree support branch angle',
        'tree_support_branch_diameter': 'Tree support branch diameter',
        'tree_support_branch_diameter_angle': 'Branch Diameter Angle',
        'tree_support_branch_diameter_organic': 'Tree support branch diameter',
        'tree_support_branch_distance': 'Tree support branch distance',
        'tree_support_branch_distance_organic': 'Tree support branch distance',
        'tree_support_brim_width': 'Tree support brim width',
        'tree_support_tip_diameter': 'Tip Diameter',
        'tree_support_top_rate': 'Branch Density',
        'tree_support_wall_count': 'Support wall loops',
        'tree_support_with_infill': 'Tree support with infill',
        'unsupported_wall_last': 'Print unsupported walls last',
        'uptodate': 'UpToDate',
        'uptodate_filaments': 'Load uptodate filament settings when using uptodate',
        'uptodate_settings': 'Load uptodate process/machine settings when using uptodate',
        'upward_compatible_machine': 'upward compatible machine',
        'use_3mf': 'Use 3MF instead of G-code',
        'use_firmware_retraction': 'Use firmware retraction',
        'use_relative_e_distances': 'Use relative E distances',
        'used_filament': 'Used filament',
        'used_filament_length': 'Filament length (meters)',
        'volumetric_speed_coefficients': 'Max volumetric speed multinomial coefficients',
        'wait_for_temp_on_wipe_tower': 'Wait for temperature on wipe tower',
        'wall_direction': 'Wall loop direction',
        'wall_distribution_count': 'Wall distribution count',
        'wall_generator': 'Wall generator',
        'wall_loops': 'Wall loops',
        'wall_maximum_deviation': 'Maximum wall deviation',
        'wall_maximum_resolution': 'Maximum wall resolution',
        'wall_sequence': 'Walls printing order',
        'wall_transition_angle': 'Wall transitioning threshold angle',
        'wall_transition_filter_deviation': 'Wall transitioning filter margin',
        'wall_transition_length': 'Wall transition length',
        'wipe': 'Wipe while retracting',
        'wipe_before_external_loop': 'Wipe before external loop',
        'wipe_distance': 'Wipe distance',
        'wipe_inward': 'Wipe inward',
        'wipe_inward_distance': 'Wipe inward distance',
        'wipe_on_loops': 'Wipe on loops',
        'wipe_speed': 'Wipe speed',
        'wipe_tower_bridging': 'Maximal bridging distance',
        'wipe_tower_cone_angle': 'Stabilization cone apex angle',
        'wipe_tower_extra_flow': 'Extra flow for purging',
        'wipe_tower_extra_rib_length': 'Extra rib length',
        'wipe_tower_extra_spacing': 'Wipe tower purge lines spacing',
        'wipe_tower_filament': 'Wipe tower',
        'wipe_tower_fillet_wall': 'Fillet wall',
        'wipe_tower_max_purge_speed': 'Maximum wipe tower print speed',
        'wipe_tower_no_sparse_layers': 'No sparse layers (beta)',
        'wipe_tower_rib_width': 'Rib width',
        'wipe_tower_rotation_angle': 'Wipe tower rotation angle',
        'wipe_tower_type': 'Wipe tower type',
        'wipe_tower_wall_type': 'Wall type',
        'wipe_tower_x': 'Position X',
        'wipe_tower_y': 'Position Y',
        'wiping_volumes_extruders': 'Purging volumes - load/unload volumes',
        'wrapping_detection_gcode': 'Clumping detection G-code',
        'wrapping_detection_layers': 'Clumping detection layers',
        'wrapping_exclude_area': 'Probing exclude area of clumping',
        'xy_contour_compensation': 'X-Y contour compensation',
        'xy_hole_compensation': 'X-Y hole compensation',
        'year': 'Year',
        'z_hop': 'Z-hop height',
        'z_hop_types': 'Z-hop type',
        'z_offset': 'Z offset',
        'zaa_dont_alternate_fill_direction': "Don't alternate fill direction",
        'zaa_enabled': 'Z contouring enabled',
        'zaa_min_z': 'Minimum Z height',
        'zaa_minimize_perimeter_height': 'Minimize wall height angle',
        'zhop': 'Current Z-hop',
    },
    "ru": {
        'accel_to_decel_enable': 'Заменять "max_accel_to_decel"',
        'accel_to_decel_factor': 'Значение',
        'activate_air_filtration': 'Вкл. вытяжной вентилятор',
        'activate_chamber_temp_control': 'Вкл. контроль температуры',
        'adaptive_bed_mesh_margin': 'Расширение области измерения',
        'adaptive_layer_height': 'Adaptive layer height',
        'adaptive_pressure_advance': 'Адаптивный PA (beta)',
        'adaptive_pressure_advance_bridges': 'Фиксированный PA на мостах',
        'adaptive_pressure_advance_model': 'Диапазон значений Pressure Advance (beta)',
        'adaptive_pressure_advance_overhangs': 'Адаптироваться к изменениям линии',
        'additional_cooling_fan_speed': 'Обдув',
        'additional_fan_full_speed_layer': 'Восстанавливать обдув на',
        'align_infill_direction_to_model': 'Относительные углы',
        'align_xy': 'Align XY',
        'allow_mix_temp': 'Allow filaments with high/low temperature to be printed together',
        'allow_multicolor_oneplate': 'Игнорировать разницу в цвете',
        'allow_newer_file': 'Разрешить нарезку 3MF более новой версии',
        'allow_rotations': 'Разрешить вращение при расстановке',
        'alternate_extra_wall': 'Чередующийся доп. периметр',
        'arrange': 'Параметры расстановки',
        'assemble': 'Объединить в сборку',
        'autosave': 'Autosave',
        'auxiliary_fan': 'Вспомогательный вентилятор',
        'avoid_extrusion_cali_region': 'Избегать зону калибровки экструзии при выполнении расстановки',
        'bbl_calib_mark_logo': 'Отображать на столе линии автокалибровки',
        'bbl_use_printhost': 'Использовать сторонний хост печати',
        'bed_custom_model': 'Пользовательская модель стола',
        'bed_custom_texture': 'Пользовательская текстура стола',
        'bed_exclude_area': 'Область исключения',
        'bed_mesh_max': 'Макс. координаты',
        'bed_mesh_min': 'Мин. координаты',
        'bed_mesh_probe_distance': 'Интервал точек измерения высот',
        'bed_temperature_formula': 'Политика нагрева стола',
        'before_layer_change_gcode': 'G-код перед сменой слоя',
        'best_object_pos': 'Наилучшее расположение модели',
        'bottom_layer_direction': 'Угол шаблона нижней поверхности',
        'bottom_shell_layers': 'Сплошных слоёв снизу',
        'bottom_shell_thickness': 'Толщина оболочки снизу',
        'bottom_solid_infill_flow_ratio': 'Поток нижней поверхности',
        'bottom_surface_density': 'Плотность нижней поверхности',
        'bottom_surface_filament_id': 'Нижняя поверхность',
        'bottom_surface_fill_order': 'Направление печати',
        'bottom_surface_pattern': 'Шаблон заполнения нижней поверхности',
        'bridge_acceleration': 'Мосты',
        'bridge_angle': 'Угол внешних мостов',
        'bridge_density': 'Плотность внешних мостов',
        'bridge_flow': 'Поток внешних мостов',
        'bridge_line_width': 'Мосты',
        'bridge_no_support': 'Не печатать поддержки под мостами',
        'bridge_speed': 'Внешние',
        'brim_ears': 'Ушки каймы',
        'brim_ears_detection_length': 'Радиус обнаружения ушек',
        'brim_ears_max_angle': 'Максимальный угол ушек',
        'brim_ears_outer_only': 'Ушки каймы только снаружи',
        'brim_flow_ratio': 'Поток каймы',
        'brim_object_gap': 'Смещение каймы',
        'brim_type': 'Тип каймы',
        'brim_use_efc_outline': 'Учитывать сдвиг контура',
        'brim_width': 'Ширина каймы',
        'center': 'По центру',
        'center_of_surface_pattern': 'Центровать шаблон по',
        'chamber_minimal_temperature': 'Стартовая',
        'chamber_temperature': 'Температура термокамеры',
        'change_extrusion_role_gcode': 'G-код при смене типа линии',
        'change_filament_gcode': 'G-код смены материала',
        'clone_objects': 'Клонировать объекты',
        'close_additional_fan_first_x_layers': 'Для первых',
        'close_fan_the_first_x_layers': 'Не обдувать первые слои',
        'combine_brims': 'Общая кайма',
        'compatible_printers': 'Профили принтеров',
        'compatible_printers_condition': 'Условия совместимости',
        'compatible_prints': 'Профили настроек',
        'compatible_prints_condition': 'Условия совместимости',
        'complete_print_exhaust_fan_speed': 'Обдув',
        'config_compatibility': 'Forward-compatibility rule when loading configurations from config files and project files (3MF, AMF).',
        'convert_unit': 'Преобразовать ед. изменения',
        'cool_plate_temp': 'Основная',
        'cool_plate_temp_initial_layer': 'Первый слой',
        'cooling_filter_enabled': 'Охлаждать через фильтр',
        'cooling_tube_length': 'Длина холодной зоны',
        'cooling_tube_retraction': 'Позиция холодной зоны',
        'copy': 'Копировать',
        'counterbore_hole_bridging': 'Опора отверстий в мостах',
        'curr_bed_type': 'Покрытие',
        'current_extruder': 'Текущий экструдер',
        'current_object_idx': 'Номер текущей модели',
        'cut': 'Разрезать/вырезать',
        'cut_grid': 'Разрезать/вырезать',
        'cut_x': 'Разрезать/вырезать',
        'cut_y': 'Разрезать/вырезать',
        'datadir': 'Папка конфигурации пользователя',
        'day': 'День',
        'debug': 'Уровень отладки журнала',
        'default_acceleration': 'По умолчанию',
        'default_bed_type': 'Тип стола по умолчанию',
        'default_filament_colour': 'Цвет по умолчанию',
        'default_filament_profile': 'Профиль материала по умолчанию',
        'default_jerk': 'По умолчанию',
        'default_junction_deviation': 'Junction Deviation',
        'default_nozzle_volume_type': 'Default Nozzle Volume Type.',
        'default_print_profile': 'Профиль настроек по умолчанию',
        'deretract_speed_extruder_change': 'Скорость возврата (смена экструдера)',
        'deretraction_speed': 'Скорость возврата',
        'detect_narrow_internal_solid_infill': 'Оптимизация заполнения узких мест',
        'detect_overhang_wall': 'Обнаруживать нависающие периметры',
        'detect_thin_wall': 'Обнаруживать тонкие стенки',
        'disable_m73': 'Не отмечать прогресс',
        'dont_filter_internal_bridges': 'Чувствительность внутренних мостов',
        'dont_slow_down_outer_wall': 'Не замедляться на внешних периметрах',
        'downward_check': 'Проверка совместимости принтера',
        'downward_settings': 'Настройка текущих принтеров',
        'draft_shield': 'Защитный кожух',
        'duplicate_grid': 'Duplicate by grid',
        'during_print_exhaust_fan_speed': 'Обдув',
        'e_position': 'Абсолютные координаты экструдера',
        'e_restart_extra': 'Дополнительная подача',
        'e_retracted': 'Откат',
        'elefant_foot_compensation': 'Компенсация «слоновьей ноги»',
        'elefant_foot_compensation_layers': 'Слои компенсации',
        'elefant_foot_layers_density': 'Плотность слоя компенсации',
        'emit_machine_limits_to_gcode': 'Отправлять в G-код',
        'enable_arc_fitting': 'Аппроксимация дугами',
        'enable_extra_bridge_layer': 'Двухслойные мосты (beta)',
        'enable_filament_dynamic_map': 'Динамическое сопоставление материалов',
        'enable_filament_ramming': 'Включить рэмминг прутка',
        'enable_mixed_color_sublayer': 'Подслой смешанного цвета',
        'enable_overhang_bridge_fan': 'Принудительный обдув нависаний и мостов',
        'enable_overhang_speed': 'Замедляться на нависаниях',
        'enable_power_loss_recovery': 'Восстановление после потери питания',
        'enable_pressure_advance': 'Включить Pressure Advance',
        'enable_prime_tower': 'Включить',
        'enable_support': 'Включить поддержку',
        'enable_timelapse': 'Вкл. таймлапс для печати',
        'enable_tower_interface_cooldown_during_tower': 'Ранний сброс температуры',
        'enable_tower_interface_features': 'Улучшенная адгезия',
        'enable_wrapping_detection': 'Обнаружение налипания пластика на сопло',
        'enforce_support_layers': 'Enforce support for the first',
        'eng_plate_temp': 'Основная',
        'eng_plate_temp_initial_layer': 'Первый слой',
        'ensure_on_bed': 'Обеспечивать размещение на столе',
        'ensure_vertical_shell_thickness': 'Сохранение толщины вертикальной оболочки',
        'exclude_object': 'Исключение объектов',
        'export_3mf': 'Экспорт в 3MF',
        'export_amf': 'Export AMF',
        'export_gcode': 'Экспорт в G-код',
        'export_obj': 'Export OBJ',
        'export_settings': 'Экспорт настроек',
        'export_sla': 'Export SLA',
        'export_slicedata': 'Экспорт данных о нарезке',
        'export_stl': 'Экспорт в STL',
        'export_stls': 'Экспорт в отдельные STL',
        'export_svg': 'Export SVG',
        'extra_loading_move': 'Дополнительная длина загрузки',
        'extra_perimeters_on_overhangs': 'Дополнительные периметры на нависаниях',
        'extra_solid_infills': 'Правило сплошных слоёв',
        'extruded_volume': 'Объём для каждого экструдера',
        'extruded_volume_total': 'Общий объём материала',
        'extruded_weight': 'Вес для каждого экструдера',
        'extruded_weight_total': 'Общий вес',
        'extruder': 'Экструдер',
        'extruder_ams_count': 'Extruder AMS count',
        'extruder_clearance_dist_to_rod': 'Distance to rod',
        'extruder_clearance_height_to_lid': 'Высота до крышки',
        'extruder_clearance_height_to_rod': 'Высота до вала',
        'extruder_clearance_radius': 'Радиус',
        'extruder_colour': 'Цвет экструдера',
        'extruder_nozzle_count': 'extruder nozzle count',
        'extruder_nozzle_stats': 'Extruder nozzle stats',
        'extruder_nozzle_volume_type': 'Extruder nozzle volume type',
        'extruder_offset': 'Смещение координат экструдера',
        'extruder_printable_area': 'Область печати экструдера',
        'extruder_printable_height': 'Предел высоты печати',
        'extruder_type': 'Тип',
        'extruder_variant_list': 'Extruder variant list',
        'extrusion_rate_smoothing_external_perimeter_only': 'Применять только к видимым\u2006элементам',
        'fan_cooling_layer_time': 'Время слоя',
        'fan_direction': 'Направление вентилятора',
        'fan_kickstart': 'Продолжительность принудительного запуска',
        'fan_max_speed': 'Обдув',
        'fan_min_speed': 'Обдув',
        'fan_speedup_overhangs': 'Только на нависаниях',
        'fan_speedup_time': 'Смещение времени запуска вентилятора',
        'farthest_point_timelapse': 'Съёмка из дальней точки',
        'filament_adaptive_volumetric_speed': 'Адаптивный расход',
        'filament_adhesiveness_category': 'Группа адгезивности',
        'filament_change_extrusion_role_gcode': 'G-код при смене типа линии (настройки материала)',
        'filament_change_length': 'Длина рэмминга',
        'filament_change_length_nc': 'Смена хотэнда',
        'filament_colour': 'Цвет',
        'filament_cooling_before_tower': 'Охлаждение на черновой башне',
        'filament_cooling_final_speed': 'Скорость последнего охлаждающего движения',
        'filament_cooling_initial_speed': 'Скорость первого охлаждающего движения',
        'filament_cooling_moves': 'Количество охлаждающих движений',
        'filament_cost': 'Стоимость',
        'filament_density': 'Плотность',
        'filament_diameter': 'Диаметр',
        'filament_end_gcode': 'Завершающий G-код',
        'filament_extruder_compatibility': 'Совместимость материала и экструдера',
        'filament_extruder_id': 'Номер текущего экструдера',
        'filament_extruder_variant': "Filament's extruder variant",
        'filament_flow_ratio': 'Коэффициент потока',
        'filament_flush_temp': 'Температура прочистки',
        'filament_flush_temp_fast': 'Температура прочистки',
        'filament_flush_volumetric_speed': 'Расход при прочистке',
        'filament_ironing_flow': 'Поток',
        'filament_ironing_inset': 'Сужение границ',
        'filament_ironing_spacing': 'Интервал линий',
        'filament_ironing_speed': 'Ограничение скорости',
        'filament_is_mixed': 'Является смешанным материалом',
        'filament_is_support': 'Материал поддержки',
        'filament_loading_speed': 'Скорость загрузки',
        'filament_loading_speed_start': 'Начальная скорость загрузки',
        'filament_map': 'Назначение материала на экструдер',
        'filament_map_2': 'Filament map plus for multi nozzle',
        'filament_map_mode': 'filament mapping mode',
        'filament_max_volumetric_speed': 'Предел объёмного расхода',
        'filament_minimal_purge_on_wipe_tower': 'Мин. объём прочистки на черновой башне',
        'filament_mixed_components': 'Компоненты смешанного материала',
        'filament_mixed_gradient': 'Градиент смешанного материала',
        'filament_mixed_gradient_curve': 'Кривая градиента смешанного материала',
        'filament_mixed_gradient_per_part': 'Градиент смешанного материала по частям',
        'filament_mixed_gradient_range': 'Диапазон градиента смешанного материала',
        'filament_mixed_sublayer_ratios': 'Доли подслоёв смешанного материала',
        'filament_multitool_ramming': 'Рэмминг для сменных насадок',
        'filament_multitool_ramming_flow': 'Объёмный расход при рэмминге',
        'filament_multitool_ramming_volume': 'Объём рэмминга',
        'filament_notes': 'Заметки о материале',
        'filament_pre_cooling_temperature': 'Смена экструдера',
        'filament_pre_cooling_temperature_nc': 'Смена хотэнда',
        'filament_preheat_temperature_delta': 'Дельта преднагрева',
        'filament_preset': 'Имя профиля материала',
        'filament_prime_volume': 'Смена материала',
        'filament_prime_volume_nc': 'Смена хотэнда',
        'filament_printable': 'Пригодный для печати',
        'filament_ramming_parameters': 'Настройки рэмминга',
        'filament_ramming_travel_time': 'Смена экструдера',
        'filament_ramming_travel_time_nc': 'Смена хотэнда',
        'filament_ramming_volumetric_speed': 'Смена экструдера',
        'filament_ramming_volumetric_speed_nc': 'Смена хотэнда',
        'filament_retract_length_nc': 'Откат при смене хотэнда',
        'filament_self_index': 'Filament self index',
        'filament_shrink': 'Компенсация усадки (XY)',
        'filament_shrinkage_compensation_z': 'Компенсация усадки (Z)',
        'filament_soluble': 'Растворимый материал',
        'filament_stamping_distance': 'Расстояние утрамбовки',
        'filament_stamping_loading_speed': 'Скорость загрузки при утрамбовке',
        'filament_start_gcode': 'Стартовый G-код',
        'filament_toolchange_delay': 'Задержка после выгрузки',
        'filament_tower_interface_pre_extrusion_dist': 'Дистанция избыточной подачи при смене',
        'filament_tower_interface_pre_extrusion_length': 'Длина прутка для избыточной подачи',
        'filament_tower_interface_print_temp': 'Температура при прочистке',
        'filament_tower_interface_purge_volume': 'Прочистка на слое интерфейса',
        'filament_tower_ironing_area': 'Разглаживание кончиков',
        'filament_type': 'Тип',
        'filament_unloading_speed': 'Скорость выгрузки',
        'filament_unloading_speed_start': 'Начальная скорость выгрузки',
        'filament_vendor': 'Производитель',
        'file_start_gcode': 'G-код заголовка файла',
        'filename_format': 'Формат имени файла',
        'fill_multiline': 'Линий заполнения',
        'filter_out_gap_fill': 'Минимальная длина щели',
        'first_layer_flow_ratio': 'Первый слой модели',
        'first_layer_print_convex_hull': 'Выпуклая оболочка первого слоя',
        'first_layer_print_max': 'Верхний правый угол ограничивающего прямоугольника первого слоя',
        'first_layer_print_min': 'Нижний левый угол ограничивающего прямоугольника первого слоя',
        'first_layer_print_sequence': 'Очерёдность материалов на первом слое',
        'first_layer_print_size': 'Размер ограничивающего прямоугольника первого слоя',
        'first_layer_sequence_choice': 'Очерёдность материалов на первом слое',
        'first_x_layer_fan_speed': 'Обдув',
        'flashforge_serial_number': 'Серийный номер',
        'flush_into_infill': 'Прочистка в заполнение',
        'flush_into_objects': 'Прочищать в эту модель',
        'flush_into_support': 'Прочистка в поддержку',
        'flush_multiplier': 'Множитель прочистки',
        'flush_multiplier_fast': 'Множитель прочистки (быстрый режим)',
        'flush_volumes_matrix': 'Объём прочистки',
        'full_fan_speed_layer': 'Восстанавливать обдув на',
        'fuzzy_skin': 'Нечёткая оболочка',
        'fuzzy_skin_first_layer': 'Применять на первом слое',
        'fuzzy_skin_layers_between_ripple_offset': 'Группировка слоёв',
        'fuzzy_skin_mode': 'Метод создания оболочки',
        'fuzzy_skin_noise_type': 'Алгоритм',
        'fuzzy_skin_octaves': 'Количество слоёв шума',
        'fuzzy_skin_persistence': 'Затухание шума нечёткой оболочки',
        'fuzzy_skin_point_distance': 'Длина сегментов',
        'fuzzy_skin_ripple_offset': 'Смещение волн',
        'fuzzy_skin_ripples_per_layer': 'Количество волн на слое',
        'fuzzy_skin_scale': 'Масштаб генерации',
        'fuzzy_skin_thickness': 'Максимальное отклонение',
        'gap_fill_flow_ratio': 'Заполнение щелей',
        'gap_fill_target': 'Заполнение щелей',
        'gap_infill_speed': 'Заполнение щелей',
        'gcode_add_line_number': 'Нумеровать строки',
        'gcode_comments': 'Подробный G-код',
        'gcode_flavor': 'Тип G-кода',
        'gcode_label_objects': 'Помечать модели',
        'gcode_skip_config_block': 'Пропустить блок конфигурации в G-code',
        'gcodeviewer': 'G-code viewer',
        'grab_length': 'Длина захвата',
        'ground_face_normal': 'Ground face by normal',
        'ground_face_point': 'Ground face at point',
        'ground_largest_face': 'Ground largest face',
        'gyroid_optimized': 'Оптимизация CRAMP (beta)',
        'has_filament_switcher': 'Автосмена материала',
        'has_single_extruder_multi_material_priming': 'Имеется предзарядка одиночного ММ экструдера',
        'has_wipe_tower': 'Имеется черновая башня',
        'head_wrap_detect_zone': 'Head wrap detect zone',
        'help': 'Помощь',
        'help_fff': 'Help (FFF options)',
        'help_sla': 'Help (SLA options)',
        'high_current_on_filament_swap': 'Повышение тока при смене прутка',
        'hole_to_polyhole': 'Многогранные отверстия',
        'hole_to_polyhole_max_edges': 'Число граней',
        'hole_to_polyhole_threshold': 'Предел обнаружения',
        'hole_to_polyhole_twisted': 'Скручивание многогранника',
        'host_type': 'Тип хоста',
        'hot_plate_temp': 'Основная',
        'hot_plate_temp_initial_layer': 'Первый слой',
        'hour': 'Час',
        'idle_temperature': 'Температура в простое',
        'ignore_nonexistent_config': 'Ignore non-existent config files',
        'independent_support_layer_height': 'Независимая высота слоя поддержки',
        'infill_anchor': 'Длина привязок шаблона заполнения',
        'infill_anchor_max': 'Предел стыковки линий шаблона',
        'infill_combination': 'Объединение слоёв заполнения',
        'infill_combination_max_layer_height': 'Предел высоты объединённого слоя',
        'infill_direction': 'Угол шаблона заполнения',
        'infill_jerk': 'Заполнение',
        'infill_lock_depth': 'Перекрытие зигзага',
        'infill_overhang_angle': 'Угол нависания заполнения',
        'infill_shift_step': 'Шаг смещения шаблона',
        'infill_wall_overlap': 'Перекрытие заполнения с периметром',
        'info': 'Информация о модели',
        'inherits': 'Наследует профиль',
        'initial_extruder': 'Начальный экструдер',
        'initial_filament_type': 'Initial filament type',
        'initial_layer_acceleration': 'Первый слой',
        'initial_layer_fan_speed': 'Обдув первого слоя',
        'initial_layer_infill_speed': 'Заполнение',
        'initial_layer_jerk': 'Первый слой',
        'initial_layer_line_width': 'Первый слой',
        'initial_layer_min_bead_width': 'Минимальная ширина периметра первого слоя',
        'initial_layer_print_height': 'Высота первого слоя',
        'initial_layer_speed': 'Первый слой',
        'initial_layer_travel_acceleration': 'Перемещения на первом слое',
        'initial_layer_travel_jerk': 'Перемещения на первом слое',
        'initial_layer_travel_speed': 'Холостые перемещения',
        'initial_tool': 'Начальный инструмент',
        'inner_wall_acceleration': 'Внутренние периметры',
        'inner_wall_filament_id': 'Внутренние периметры',
        'inner_wall_flow_ratio': 'Внутренние периметры',
        'inner_wall_jerk': 'Внутренние периметры',
        'inner_wall_line_width': 'Внутренние периметры',
        'inner_wall_speed': 'Внутренние периметры',
        'input_filename_base': 'Имя входного файла без расширения',
        'input_shaping_damp_x': 'X',
        'input_shaping_damp_y': 'Y',
        'input_shaping_emit': 'Гашение эха',
        'input_shaping_freq_x': 'X',
        'input_shaping_freq_y': 'Y',
        'input_shaping_type': 'Тип шейпера',
        'inspect_mesh': 'Inspect mesh (JSON to stdout)',
        'inspect_paint': 'Inspect paint (JSON to stdout)',
        'interface_shells': 'Связующие оболочки',
        'interlocking_beam': 'Создать взаимосвязанную структуру',
        'interlocking_beam_layer_count': 'Количество слоёв взаимосвязанных балок',
        'interlocking_beam_width': 'Ширина взаимосвязанных балок',
        'interlocking_boundary_avoidance': 'Избегание границ взаимосвязанной структуры',
        'interlocking_depth': 'Глубина взаимосвязанной структуры',
        'interlocking_orientation': 'Направление взаимосвязанных балок',
        'internal_bridge_angle': 'Угол внутренних мостов',
        'internal_bridge_density': 'Плотность внутренних мостов',
        'internal_bridge_fan_speed': 'Обдув внутренних мостов',
        'internal_bridge_flow': 'Поток внутренних мостов',
        'internal_bridge_speed': 'Внутренние',
        'internal_solid_filament_id': 'Сплошное заполнение',
        'internal_solid_infill_acceleration': 'Сплошное заполнение',
        'internal_solid_infill_flow_ratio': 'Сплошное заполнение',
        'internal_solid_infill_line_width': 'Сплошное заполнение',
        'internal_solid_infill_pattern': 'Шаблон сплошного заполнения',
        'internal_solid_infill_speed': 'Сплошное заполнение',
        'ironing_angle': 'Относительный угол',
        'ironing_angle_fixed': 'Фиксированный угол',
        'ironing_expansion': 'Расширение разглаживания',
        'ironing_fan_speed': 'Обдув разглаживания',
        'ironing_flow': 'Поток',
        'ironing_inset': 'Сужение границ',
        'ironing_pattern': 'Шаблон разглаживания',
        'ironing_spacing': 'Интервал линий',
        'ironing_speed': 'Ограничение скорости',
        'ironing_type': 'Тип разглаживания',
        'is_extruder_used': 'Используется ли экструдер?',
        'is_infill_first': 'Сначала печатать заполнение',
        'lateral_lattice_angle_1': 'Наклон боковой сетки 1',
        'lateral_lattice_angle_2': 'Наклон боковой сетки 2',
        'layer_change_gcode': 'G-код после смены слоя',
        'layer_height': 'Высота слоя',
        'layer_num': 'Номер слоя',
        'layer_z': 'Высота слоя над столом',
        'lightning_overhang_angle': 'Наклон поверхности для поддержки молнией',
        'lightning_prune_angle': 'Наклон опор',
        'lightning_straightening_angle': 'Наклон локальных искажений',
        'line_width': 'По умолчанию',
        'load': 'Load config file',
        'load_assemble_list': 'Загрузить список сборки',
        'load_custom_gcodes': 'Загрузить пользовательский G-код',
        'load_defaultfila': 'Загрузить материал по умолчанию',
        'load_filament_ids': 'Загрузить идентификаторы материалов',
        'load_filaments': 'Загрузка настроек материала',
        'load_settings': 'Загрузка общих настроек',
        'load_slicedata': 'Загрузка данных о нарезке',
        'logfile': 'Файл журнала',
        'long_retractions_when_cut': 'Обрезать пруток ближе к кончику (beta)',
        'long_retractions_when_ec': 'Длинный откат перед сменой экструдера',
        'machine_end_gcode': 'Завершающий G-код',
        'machine_hotend_change_time': 'Время смены хотэнда',
        'machine_load_filament_time': 'Время загрузки прутка',
        'machine_pause_gcode': 'G-код паузы печати',
        'machine_start_gcode': 'Стартовый G-код',
        'machine_tool_change_time': 'Время смены инструмента',
        'machine_unload_filament_time': 'Время выгрузки прутка',
        'make_overhang_printable': 'Деформировать модель для печати без поддержек',
        'make_overhang_printable_angle': 'Допустимый наклон',
        'make_overhang_printable_hole_size': 'Площадь допустимых отверстий',
        'makerlab_name': 'Имя MakerLab',
        'makerlab_version': 'Версия MakerLab',
        'manual_filament_change': 'Ручная смена прутка',
        'master_extruder_id': 'Master extruder id',
        'max_bridge_length': 'Максимальный интервал опор',
        'max_layer_height': 'Макс.',
        'max_layer_z': 'Макс. высота слоя над столом',
        'max_resonance_avoidance_speed': 'Макс.',
        'max_travel_detour_distance': 'Максимальная длина обхода',
        'max_volumetric_extrusion_rate_slope': 'Сглаживание расхода',
        'max_volumetric_extrusion_rate_slope_segment_length': 'Протяжённость сглаживания',
        'metadata_name': 'Список имён метаданных',
        'metadata_value': 'Список значений метаданных',
        'min_bead_width': 'Минимальная ширина периметра',
        'min_feature_size': 'Допустимая ширина элемента',
        'min_layer_height': 'Мин.',
        'min_length_factor': 'Допустимая длина щели',
        'min_resonance_avoidance_speed': 'Мин.',
        'min_save': 'Минимальное сохранение',
        'min_skirt_length': 'Мин. расход для юбки',
        'min_width_top_surface': 'Порог верхней поверхности',
        'minimum_sparse_infill_area': 'Заполнять области менее',
        'minute': 'Минута',
        'mmu_segmented_region_interlocking_depth': 'Глубина переплетения окрашенной области',
        'mmu_segmented_region_max_width': 'Глубина проникновения окрашенной области',
        'month': 'Месяц',
        'mstpp': 'mstpp',
        'mtcpp': 'mtcpp',
        'no_check': 'Без проверки',
        'normal_print_time': 'Время печати (обычный режим)',
        'normative_check': 'Нормативная проверка',
        'notes': 'Примечания к конфигурации',
        'nozzle_diameter': 'Диаметр сопла',
        'nozzle_height': 'Высота сопла',
        'nozzle_hrc': 'Твёрдость сопла (HRC)',
        'nozzle_temperature': 'Основная',
        'nozzle_temperature_initial_layer': 'Первый слой',
        'nozzle_temperature_range_high': 'Макс.',
        'nozzle_temperature_range_low': 'Мин.',
        'nozzle_type': 'Материал сопла',
        'nozzle_volume': 'Объём сопла',
        'nozzle_volume_type': 'Nozzle Volume Type',
        'num_extruders': 'Количество экструдеров',
        'num_instances': 'Количество копий',
        'num_objects': 'Количество моделей',
        'num_printing_extruders': 'Number of printing extruders',
        'only_one_wall_first_layer': 'Только один периметр на первом слое',
        'only_one_wall_top': 'Только один периметр на верхней поверхности',
        'ooze_prevention': 'Включить',
        'orient': 'Параметры ориентации',
        'other_layers_print_sequence': 'Очерёдность материалов на других слоях',
        'other_layers_print_sequence_nums': 'Количество других слоёв при последовательной печати',
        'other_layers_sequence_choice': 'Очерёдность материалов на других слоях',
        'outer_wall_acceleration': 'Внешние периметры',
        'outer_wall_filament_id': 'Внешние периметры',
        'outer_wall_flow_ratio': 'Внешние периметры',
        'outer_wall_jerk': 'Внешние периметры',
        'outer_wall_line_width': 'Внешние периметры',
        'outer_wall_speed': 'Внешние периметры',
        'output': 'Output File',
        'outputdir': 'Папку сохранения',
        'overhang_1_4_speed': '10%',
        'overhang_2_4_speed': '25%',
        'overhang_3_4_speed': '50%',
        'overhang_4_4_speed': '75%',
        'overhang_fan_speed': 'Обдув нависаний и внешних мостов',
        'overhang_fan_threshold': 'Мин. вынос нависающей линии для обдува',
        'overhang_flow_ratio': 'Нависания',
        'overhang_reverse': 'Реверс на чётных слоях',
        'overhang_reverse_internal_only': 'Реверс только для внутренних периметров',
        'overhang_reverse_threshold': 'Порог для реверса',
        'parallel_printheads_bed_exclude_areas': 'Области исключения для зависимых голов',
        'parallel_printheads_count': 'Количество зависимых голов',
        'parking_pos_retraction': 'Положение парковки прутка',
        'part_cooling_fan_min_pwm': 'Скорость страгивания',
        'pellet_flow_coefficient': 'Поток гранул',
        'pellet_modded_printer': 'Гранульная модификация принтера',
        'physical_extruder_map': 'Map the logical extruder to physical extruder',
        'physical_printer_preset': 'Имя физического принтера',
        'pipe': 'Send progress to pipe',
        'plugins': 'Используемые плагины',
        'position': 'Позиция',
        'post_process': 'Скрипты постобработки',
        'precise_outer_wall': 'Точные периметры',
        'precise_z_height': 'Точная высота по Z',
        'preferred_orientation': 'Предпочтительная ориентация',
        'preheat_steps': 'Шагов преднагрева',
        'preheat_time': 'Время преднагрева',
        'preset_names': 'Имена профиля принтера',
        'pressure_advance': 'Коэффициент PA',
        'prime_tower_brim_width': 'Ширина каймы',
        'prime_tower_enable_framework': 'Внутренние рёбра',
        'prime_tower_infill_gap': 'Интервал между линиями',
        'prime_tower_skip_points': 'Защитные окна',
        'prime_tower_width': 'Ширина',
        'prime_volume': 'Объём сброса материала на черновой башне',
        'prime_volume_mode': 'Режим прочистки',
        'print_bed_max': 'Верхний правый угол ограничивающего прямоугольника печатного стола',
        'print_bed_min': 'Нижний левый угол ограничивающего прямоугольника печатного стола',
        'print_bed_size': 'Размер прямоугольной рамки, ограничивающей область печати',
        'print_extruder_id': 'Print extruder id',
        'print_extruder_variant': "Print's extruder variant",
        'print_flow_ratio': 'Коэффициент потока',
        'print_host': 'Имя хоста, IP/URL-адрес',
        'print_host_webui': 'URL-адрес хоста',
        'print_order': 'Очерёдность моделей',
        'print_preset': 'Имя профиля печати',
        'print_sequence': 'Печать моделей',
        'print_time': 'Время печати (обычный режим)',
        'print_time_sec': 'Время печати (в секундах)',
        'printable_area': 'Область печати',
        'printable_height': 'Высота печати',
        'printer_agent': 'Сетевой агент',
        'printer_extruder_id': 'Printer extruder id',
        'printer_extruder_variant': "Printer's extruder variant",
        'printer_model': 'Тип принтера',
        'printer_notes': 'Примечания к принтеру',
        'printer_preset': 'Имя профиля принтера',
        'printer_structure': 'Кинематика принтера',
        'printer_technology': 'Технология принтера',
        'printer_variant': 'Модификация принтера',
        'printhost_apikey': 'API-ключ / пароль',
        'printhost_authorization_type': 'Тип авторизации',
        'printhost_cafile': 'Файл корневого сертификата HTTPS',
        'printhost_password': 'Пароль',
        'printhost_port': 'Принтер',
        'printhost_ssl_ignore_revoke': 'Игнорировать проверки отзыва сертификата',
        'printhost_user': 'Пользователь',
        'printing_by_object_gcode': 'G-код между моделями',
        'printing_filament_types': 'Used filament types',
        'process_change_extrusion_role_gcode': 'G-код при смене типа линии (настройки печати)',
        'purge_in_prime_tower': 'Прочистка в черновую башню',
        'raft_contact_distance': 'Зазор под моделью',
        'raft_expansion': 'Расширение подложки',
        'raft_first_layer_density': 'Плотность первого слоя',
        'raft_first_layer_expansion': 'Расширение первого слоя',
        'raft_layers': 'Слоёв в подложке',
        'reduce_crossing_wall': 'Избегать пересечения периметров',
        'reduce_fan_stop_start_freq': 'Постоянный обдув',
        'reduce_infill_retraction': 'Откат только при пересечении периметров',
        'relative_bridge_angle': 'Относительный угол',
        'repair': 'Repair',
        'repetitions': 'Количество повторений',
        'resolution': 'Разрешение',
        'resonance_avoidance': 'Избегание ряби',
        'retract_after_wipe': 'Вторичный откат',
        'retract_before_wipe': 'Первичный откат',
        'retract_length_toolchange': 'Длина отката (смена инструмента)',
        'retract_lift_above': 'Приподнимать не ниже',
        'retract_lift_below': 'Приподнимать не выше',
        'retract_lift_enforce': 'Область применения',
        'retract_restart_extra': 'Доп. подача после отката',
        'retract_restart_extra_toolchange': 'Доп. подача после отката (смена инструмента)',
        'retract_when_changing_layer': 'Откат при смене слоя',
        'retraction_distances_when_cut': 'Длина втягивания перед обрезкой',
        'retraction_distances_when_ec': 'Длина отката перед сменой экструдера',
        'retraction_length': 'Длина',
        'retraction_minimum_travel': 'Порог перемещения',
        'retraction_speed': 'Скорость отката',
        'role_based_wipe_speed': 'Местная скорость очистки',
        'rotate': 'Вращение',
        'rotate_x': 'Поворот вокруг оси X',
        'rotate_y': 'Поворот вокруг оси Y',
        'scale': 'Масштаб для каждой модели',
        'scale_to_fit': 'Scale to Fit',
        'scan_first_layer': 'Проверка первого слоя',
        'scarf_angle_threshold': 'Порог угла для косого шва',
        'scarf_joint_flow_ratio': 'Поток косого шва',
        'scarf_joint_speed': 'Скорость косого шва',
        'scarf_overhang_threshold': 'Порог нависания',
        'seam_gap': 'Зазор шва',
        'seam_position': 'Позиция шва',
        'seam_slope_conditional': 'Ограничения косого шва',
        'seam_slope_entire_loop': 'Косой шов вдоль всего периметра',
        'seam_slope_inner_walls': 'Косой шов для внутренних периметров',
        'seam_slope_min_length': 'Длина косого шва',
        'seam_slope_start_height': 'Начальная высота косого шва',
        'seam_slope_steps': 'Шагов косого шва',
        'seam_slope_type': 'Косой шов (beta)',
        'second': 'Секунд',
        'separated_infills': 'Независимые шаблоны',
        'set_other_flow_ratios': 'Другие настройки потока',
        'silent_mode': 'Поддержка тихого режима',
        'silent_print_time': 'Время печати (тихий режим)',
        'single_extruder_multi_material': 'Общий экструдер',
        'single_extruder_multi_material_priming': 'Подготовка всех печатающих экструдеров',
        'single_instance': 'Single instance mode',
        'single_loop_draft_shield': 'Один контур после первого слоя',
        'skeleton_infill_density': 'Плотность зигзага',
        'skeleton_infill_line_width': 'Ширина линии зигзага',
        'skin_infill_density': 'Плотность оболочки',
        'skin_infill_depth': 'Область оболочки',
        'skin_infill_line_width': 'Ширина линии оболочки',
        'skip_modified_gcodes': 'Пропуск модифицированного G-кода в 3MF-файле',
        'skip_objects': 'Исключить объекты',
        'skirt_distance': 'Смещение юбки',
        'skirt_height': 'Слоёв юбки',
        'skirt_loops': 'Контуров юбки',
        'skirt_speed': 'Скорость юбки',
        'skirt_start_angle': 'Начальная точка юбки',
        'skirt_type': 'Тип юбки',
        'slice': 'Нарезать',
        'slice_closing_radius': 'Радиус закрытия зазоров полигональной сетки',
        'slicing_mode': 'Режим нарезки',
        'slicing_pipeline_plugin': 'Плагин конвейера нарезки',
        'slow_down_for_layer_cooling': 'Замедлять печать для охлаждения слоёв',
        'slow_down_layer_time': 'Время слоя',
        'slow_down_layers': 'Количество медленных слоёв',
        'slow_down_min_speed': 'Предел замедления',
        'slowdown_for_curled_perimeters': 'Замедляться на изогнутых периметрах',
        'small_area_infill_flow_compensation': 'Компенсация потока небольших областей (beta)',
        'small_area_infill_flow_compensation_model': 'Модель компенсации потока',
        'small_perimeter_speed': 'Короткие периметры',
        'small_perimeter_threshold': 'Порог коротких периметров',
        'small_support_perimeter_speed': 'Короткие периметры поддержек',
        'small_support_perimeter_threshold': 'Порог коротких периметров поддержек',
        'solid_infill_direction': 'Угол шаблона сплошного заполнения',
        'solid_infill_rotate_template': 'Правило поворота шаблона заполнения',
        'spaghetti_detector': 'Enable spaghetti detector',
        'sparse_infill_acceleration': 'Заполнение',
        'sparse_infill_density': 'Плотность заполнения',
        'sparse_infill_filament_id': 'Заполнение',
        'sparse_infill_flow_ratio': 'Заполнение',
        'sparse_infill_line_width': 'Заполнение',
        'sparse_infill_pattern': 'Шаблон заполнения',
        'sparse_infill_rotate_template': 'Правило поворота шаблона заполнения',
        'sparse_infill_smooth_factor': 'Коэффициент сглаживания заполнения',
        'sparse_infill_speed': 'Заполнение',
        'spiral_finishing_flow_ratio': 'Поток конца контура',
        'spiral_mode': 'Режим вазы',
        'spiral_mode_max_xy_smoothing': 'Радиус выборки',
        'spiral_mode_smooth': 'Сглаживание слоёв вазы',
        'spiral_starting_flow_ratio': 'Поток начала контура',
        'split': 'Разделить',
        'staggered_inner_seams': 'Смещать внутренние швы',
        'standby_temperature_delta': 'Разница температур',
        'start_end_points': 'Начальные и конечные точки',
        'strict': 'Strict mode',
        'supertack_plate_temp': 'Основная',
        'supertack_plate_temp_initial_layer': 'Первый слой',
        'support_air_filtration': 'Вытяжной вентилятор',
        'support_angle': 'Угол шаблона поддержки',
        'support_base_pattern': 'Шаблон поддержки',
        'support_base_pattern_spacing': 'Отступ между линиями поддержки',
        'support_bottom_interface_spacing': 'Отступ между линиями связующего слоя снизу',
        'support_bottom_z_distance': 'Зазор поддержки снизу',
        'support_chamber_temp_control': 'Контроль температуры в термокамере',
        'support_critical_regions_only': 'Поддержка только критических областей',
        'support_expansion': 'Горизонтальное расширение поддержки',
        'support_fast_purge_mode': 'Режим быстрой прочистки',
        'support_filament': 'Поддержка/подложка',
        'support_flow_ratio': 'Поддержки',
        'support_interface_bottom_layers': 'Связующие слои снизу',
        'support_interface_filament': 'Связующий слой поддержки/подложки',
        'support_interface_flow_ratio': 'Связующие слои',
        'support_interface_loop_pattern': 'Связующий слой петлями',
        'support_interface_not_for_body': 'Избегать исп. материала связующего слоя для поддержки',
        'support_interface_pattern': 'Шаблон связующего слоя',
        'support_interface_spacing': 'Отступ между линиями связующего слоя сверху',
        'support_interface_speed': 'Связующий слой',
        'support_interface_top_layers': 'Связующие слои сверху',
        'support_ironing': 'Разглаживать связующий слой поддержки',
        'support_ironing_flow': 'Поток разглаживания поддержки',
        'support_ironing_pattern': 'Шаблон разглаживания поддержки',
        'support_ironing_spacing': 'Расстояние между линиями разглаживания поддержки',
        'support_line_width': 'Поддержки',
        'support_material_interface_fan_speed': 'Обдув связующего слоя',
        'support_multi_bed_types': 'Сменные покрытия стола',
        'support_object_first_layer_gap': 'Отступ на первом слое',
        'support_object_xy_distance': 'Отступ от модели',
        'support_on_build_plate_only': 'Поддержка только от стола',
        'support_parallel_printheads': 'Поддержка параллельных печатающих голов',
        'support_remove_small_overhang': 'Игнорировать небольшие нависания',
        'support_speed': 'Поддержки',
        'support_style': 'Стиль',
        'support_threshold_angle': 'Максимальный угол',
        'support_threshold_overlap': 'Минимальный вынос',
        'support_top_z_distance': 'Зазор поддержки сверху',
        'support_type': 'Тип',
        'sw_renderer': 'Render with a software renderer',
        'symmetric_infill_y_axis': 'Отразить шаблон',
        'temperature_vitrification': 'Температура размягчения',
        'template_custom_gcode': 'Пользовательский G-код',
        'textured_cool_plate_temp': 'Основная',
        'textured_cool_plate_temp_initial_layer': 'Первый слой',
        'textured_plate_temp': 'Основная',
        'textured_plate_temp_initial_layer': 'Первый слой',
        'thick_bridges': 'Круглые внешние мосты',
        'thick_internal_bridges': 'Круглые внутренние мосты',
        'thumbnails': 'Эскизы в G-коде',
        'thumbnails_format': 'Формат эскизов G-кода',
        'time_cost': 'Стоимость часа печати',
        'time_lapse_gcode': 'G-код таймлапса',
        'timelapse_type': 'Таймлапсы',
        'timestamp': 'Временная метка',
        'tool_change_on_wipe_tower': 'Менять материал над башней',
        'toolchange_cyclic_first_layer': 'Apply cyclic order to first layer',
        'toolchange_cyclic_order': 'Cyclic order',
        'toolchange_ordering': 'Порядок смены материала',
        'top_bottom_infill_wall_overlap': 'Перекрытие заполнения поверхности с периметром',
        'top_layer_direction': 'Угол шаблона верхней поверхности',
        'top_shell_layers': 'Сплошных слоёв сверху',
        'top_shell_thickness': 'Толщина оболочки сверху',
        'top_solid_infill_flow_ratio': 'Поток верхней поверхности',
        'top_surface_acceleration': 'Верхняя поверхность',
        'top_surface_density': 'Плотность верхней поверхности',
        'top_surface_expansion': 'Расширение поверхностей',
        'top_surface_expansion_direction': 'Направление расширения',
        'top_surface_expansion_margin': 'Отступ от края',
        'top_surface_filament_id': 'Верхняя поверхность',
        'top_surface_fill_order': 'Направление печати',
        'top_surface_jerk': 'Верхняя поверхность',
        'top_surface_line_width': 'Верхняя поверхность',
        'top_surface_pattern': 'Шаблон заполнения верхней поверхности',
        'top_surface_speed': 'Верхняя поверхность',
        'total_cost': 'Общая стоимость',
        'total_layer_count': 'Общее количество слоёв',
        'total_toolchanges': 'Число смен инструмента',
        'total_weight': 'Общий вес',
        'total_wipe_tower_cost': 'Затраты на черновую башню',
        'total_wipe_tower_filament': 'Объём черновой башни',
        'travel_acceleration': 'Перемещения',
        'travel_jerk': 'Перемещения',
        'travel_slope': 'Угол подъёма',
        'travel_speed': 'Перемещения',
        'travel_speed_z': 'Z travel',
        'tree_support_angle_slow': 'Основной наклон ветвей',
        'tree_support_auto_brim': 'Автоширина каймы',
        'tree_support_branch_angle': 'Макс. наклон ветвей',
        'tree_support_branch_angle_organic': 'Макс. наклон ветвей',
        'tree_support_branch_diameter': 'Диаметр ветвей',
        'tree_support_branch_diameter_angle': 'Конусность поддержки',
        'tree_support_branch_diameter_organic': 'Диаметр ветвей',
        'tree_support_branch_distance': 'Расстояние между ветвями',
        'tree_support_branch_distance_organic': 'Расстояние между ветвями',
        'tree_support_brim_width': 'Ширина каймы древовидной поддержки',
        'tree_support_tip_diameter': 'Диаметр кончиков ветвей',
        'tree_support_top_rate': 'Плотность ветвей',
        'tree_support_wall_count': 'Периметры поддержки',
        'tree_support_with_infill': 'Древовидная поддержка с заполнением',
        'unsupported_wall_last': 'Print unsupported walls last',
        'uptodate': 'Актуальная версия',
        'uptodate_filaments': 'Загрузить обновлённые настройки материала при использовании обновления',
        'uptodate_settings': 'Загрузить настройки печати/принтера при использовании обновления',
        'upward_compatible_machine': 'условия для совместимых принтеров',
        'use_3mf': 'Сжатие G-кода перед отправкой',
        'use_firmware_retraction': 'Откат на уровне прошивки',
        'use_relative_e_distances': 'Относительные координаты экструдера',
        'used_filament': 'Расход прутка',
        'used_filament_length': 'Длина материала (в метрах)',
        'volumetric_speed_coefficients': 'Коэффициенты расчёта максимального расхода',
        'wait_for_temp_on_wipe_tower': 'Ожидание температуры на черновой башне',
        'wall_direction': 'Направление печати периметров',
        'wall_distribution_count': 'Количество изменяемых периметров',
        'wall_generator': 'Генератор периметров',
        'wall_loops': 'Периметры',
        'wall_maximum_deviation': 'Предельное отклонение',
        'wall_maximum_resolution': 'Минимальная длина сегмента',
        'wall_sequence': 'Порядок печати периметров',
        'wall_transition_angle': 'Порог\u2005угла\u2005для\u2009уплотнения',
        'wall_transition_filter_deviation': 'Допустимое отклонение ширины',
        'wall_transition_length': 'Длина уплотнения',
        'wipe': 'Очистка сопла при откате',
        'wipe_before_external_loop': 'Смещённая подача перед внешним периметром',
        'wipe_distance': 'Длина движения очистки',
        'wipe_inward': 'Wipe inward',
        'wipe_inward_distance': 'Wipe inward distance',
        'wipe_on_loops': 'Сброс давления на шве',
        'wipe_speed': 'Скорость очистки',
        'wipe_tower_bridging': 'Максимальная длина моста',
        'wipe_tower_cone_angle': 'Угол вершины стабилизирующего конуса',
        'wipe_tower_extra_flow': 'Дополнительный поток для очистки',
        'wipe_tower_extra_rib_length': 'Вынос основания ребра',
        'wipe_tower_extra_spacing': 'Расстояние между линиями очистки черновой башни',
        'wipe_tower_filament': 'Черновая башня',
        'wipe_tower_fillet_wall': 'Скруглять углы',
        'wipe_tower_max_purge_speed': 'Макс. скорость печати черновой башни',
        'wipe_tower_no_sparse_layers': 'Без разреженных слоёв (beta)',
        'wipe_tower_rib_width': 'Ширина ребра',
        'wipe_tower_rotation_angle': 'Угол поворота черновой башни',
        'wipe_tower_type': 'Тип черновой башни',
        'wipe_tower_wall_type': 'Форма черновой башни',
        'wipe_tower_x': 'Position X',
        'wipe_tower_y': 'Position Y',
        'wiping_volumes_extruders': 'Объём очистки - Объём загрузки/выгрузки',
        'wrapping_detection_gcode': 'G-код при обнаружении налипшего пластика',
        'wrapping_detection_layers': 'Слои обнаружения',
        'wrapping_exclude_area': 'Исключаемая область обнаружения',
        'xy_contour_compensation': 'Расширение контура слоя',
        'xy_hole_compensation': 'Расширение пустот в слое',
        'year': 'Год',
        'z_hop': 'Высота подъёма',
        'z_hop_types': 'Тип подъёма',
        'z_offset': 'Смещение координат оси Z',
        'zaa_dont_alternate_fill_direction': 'Отключить поворот шаблона заполнения',
        'zaa_enabled': 'Сглаживание слоёв',
        'zaa_min_z': 'Сдвиг допустимой высоты',
        'zaa_minimize_perimeter_height': 'Угол прижима периметров',
        'zhop': 'Подъём оси Z',
    },
}
