"""Разделы пресетов слайсера для сбора контекста."""

# Разделы пресетов: ключ результата → (атрибут коллекции, поля для full_config_value).
PRESET_SECTIONS: dict[str, tuple[str, tuple[str, ...]]] = {
    "printer": (
        "printers",
        (
            "printer_model",
            "nozzle_diameter",
            "printable_height",
            "printable_width",
            "printable_depth",
            "printer_technology",
            "bed_shape",
            "bed_length",
            "bed_width",
            "max_print_height",
            "heated_bed",
            "heated_chamber",
            "chamber_temperature",
            "notes",
            "printer_notes",
            "machine_start_gcode",
            "machine_end_gcode",
        ),
    ),
    "filament": (
        "filaments",
        (
            "filament_type",
            "filament_vendor",
            "filament_density",
            "filament_cost",
            "filament_flow_ratio",
            "filament_flow_ratio_initial_layer",
            "nozzle_temperature",
            "nozzle_temperature_initial_layer",
            "bed_temperature",
            "chamber_temperature",
            "notes",
            "filament_notes",
        ),
    ),
    "print": (
        "prints",
        (
            "layer_height",
            "initial_layer_print_height",
            "line_width",
            "wall_loops",
            "sparse_infill_density",
            "sparse_infill_pattern",
            "enable_support",
            "support_type",
            "default_print_speed",
            "outer_wall_speed",
            "travel_speed",
            "brim_type",
            "brim_width",
            "ironing_type",
            "notes",
            "print_notes",
        ),
    ),
}
